_target_: dao.pl_modules.FTModels.CrystGenerativeFinetuneModel
time_dim: 256
diffuse: True
pred_scalar: False
latent_dim: 0
cost_coord: 1.
cost_lattice: 1.
cost_scalar: 1.
max_neighbors: 20  # maximum number of neighbors for OTF graph bulding in decoder
radius: 7.  # maximum search radius for OTF graph building in decoder
timesteps: 1000
pretrain_repr: 
finetune_energy: False
energy_guidance: False


defaults:
  - decoder: crysformer
  - beta_scheduler: cosine
  - sigma_scheduler: wrapped
